### ISSUE TITLE
Adding Clock widget doesn't work

### ISSUE THREAD

**Issue by Ethanol10** [Archfx/duo-de#84]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 2
- GSI version: 2024.10.22
- Vendor version:

### Expected Behavior

Adding a widget to the homepage should place the widget and allow it to be resized.

### Current Behavior

Currently, you are able to select the widget, but when back on the home page it disappears with the bounding box left.

### Steps to Reproduce

1. Long press on home page
2. Select widgets
3. Select a widget to place
4. Tap Add
5. Current issue appears with just a bounding box around where the widget should be.

**Comment by sir86** [comment]
I dont have this issue on my end

**Comment by Ethanol10** [comment]
![9789](https://github.com/user-attachments/assets/60369d3f-f7ef-48e3-a002-2947952bc754)

This is what I see when placing a widget.

**Comment by Sidefix** [comment]
I also can't reproduce this. My homescreen is quite littered with widgets. I am on SD1.

Is this for a specific app, or any app?

**Comment by Ethanol10** [comment]
all my widgets are failing to show up, though a few days ago the google widget showed up again. Still can't place any widgets down though.

**Comment by Ethanol10** [comment]
I tried again recently and now clock seems to be the only widget that's failing, on a new installation this issue isn't present, I will chalk this up to a one off error

**Comment by sir86** [comment]
happend to me recently on duo 1 but it seems to affect all wigets that need confirm click after put on dektop.

**Comment by Ethanol10** [comment]
Yeah, I'll reopen it if it's happening to others

**Comment by Ethanol10** [comment]
Funny issue is I managed to quickly get it to work, by tapping through the process really fast, but I could not resize it.

**Comment by juapalso** [comment]
I am with the latest version from 127/11 and the clock widget does not work for me

**Comment by Ethanol10** [comment]
In vanilla, the Clock app seems to work, but that seems to be because it might be an entirely separate app. Is there a unique Clock app that is installed from Gapps?

**Comment by Darkaxt** [comment]
Another one with the widget issue and my bottom shortcuts were also vanished. I use Taskbar as a replacement.

**Comment by itsleemcguire** [comment]
I lso have this issue with a lot of widgets

**Comment by Clanceeinfinity** [comment]
adding a google photos widget crashes trebuchet.

**Comment by Clanceeinfinity** [comment]
actually every widget crashes that uses the widget editor

**Comment by Clanceeinfinity** [comment]
![Screenshot_20241217-231035](https://github.com/user-attachments/assets/a22735cb-86d5-4519-bb76-be907ca15b19)
this is what i mean btw, if you have another device try this and it should look like this. on the duo2 for me it just crashes the launcher on doesn't do anything. on android 14, you could bypass this by deactivating every desktop ui feature.

**Comment by Ethanol10** [comment]
Log on the issue:
```
2024-12-19 12:13:14.025 12101-12101 b/267448330             com.android.launcher3                D  provider: ComponentInfo{com.google.android.deskclock/com.android.alarmclock.DigitalAppWidgetProvider}, paddedSizes: [331.19168x298.03107, 331.19168x298.03107, 435.23312x199.79274, 435.23312x199.79274], getMinMaxSizes: Rect(331, 199 - 435, 298)
2024-12-19 12:13:14.038  2967-3179  ActivityManager         system_server                        D  sync unfroze 12079 com.google.android.deskclock for 3
2024-12-19 12:13:14.042  2967-6483  AppWidgetServiceImpl    system_server                        I  Bound widget 3 to provider ProviderId{user:0, app:10186, cmp:ComponentInfo{com.google.android.deskclock/com.android.alarmclock.DigitalAppWidgetProvider}}
2024-12-19 12:13:14.043 12101-12101 AndroidRuntime          com.android.launcher3                D  Shutting down VM
2024-12-19 12:13:14.044 12101-12101 AndroidRuntime          com.android.launcher3                E  FATAL EXCEPTION: main
                                                                                                    Process: com.android.launcher3, PID: 12101
                                                                                                    java.lang.IllegalArgumentException: Cannot find ActivityContext in parent tree
                                                                                                    	at com.android.launcher3.views.ActivityContext.lookupContext(ActivityContext.java:510)
                                                                                                    	at com.android.launcher3.util.ActivityOptionsWrapper.toBundle(ActivityOptionsWrapper.java:57)
                                                                                                    	at com.android.launcher3.widget.LauncherWidgetHolder.getConfigurationActivityOptions(LauncherWidgetHolder.java:243)
                                                                                                    	at com.android.launcher3.widget.LauncherWidgetHolder.startConfigActivity(LauncherWidgetHolder.java:221)
                                                                                                    	at com.android.launcher3.widget.WidgetAddFlowHandler.startConfigActivity(WidgetAddFlowHandler.java:80)
                                                                                                    	at com.android.launcher3.Launcher.addAppWidgetImpl(Launcher.java:1868)
                                                                                                    	at com.android.launcher3.Launcher.addAppWidgetFromDropImpl(Launcher.java:1858)
                                                                                                    	at com.android.launcher3.Launcher.addAppWidgetFromDrop(Launcher.java:1966)
                                                                                                    	at com.android.launcher3.Launcher.addPendingItem(Launcher.java:1915)
                                                                                                    	at com.android.launcher3.accessibility.LauncherAccessibilityDelegate.lambda$addToWorkspace$5(LauncherAccessibilityDelegate.java:429)
                                                                                                    	at com.android.launcher3.accessibility.LauncherAccessibilityDelegate.$r8$lambda$PyIa6ZqM3GhI-IMadFjVVelLYzQ(Unknown Source:0)
                                                                                                    	at com.android.launcher3.accessibility.LauncherAccessibilityDelegate$$ExternalSyntheticLambda8.run(D8$$SyntheticClass:0)
                                                                                                    	at com.android.launcher3.PagedView.onPageEndTransition(PagedView.java:513)
                                                                                                    	at com.android.launcher3.Workspace.onPageEndTransition(Workspace.java:1223)
                                                                                                    	at com.android.launcher3.PagedView.pageEndTransition(PagedView.java:478)
                                                                                                    	at com.android.launcher3.PagedView.draw(PagedView.java:1960)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23700)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23654)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23654)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23654)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23654)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:23654)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5659)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5312)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4303)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:945)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
2024-12-19 12:13:14.044 12101-12101 AndroidRuntime          com.android.launcher3                E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2024-12-19 12:13:14.046  2967-12392 DropBoxManagerService   system_server                        I  add tag=system_app_crash isTagEnabled=true flags=0x2
2024-12-19 12:13:14.047  2967-6483  ActivityTaskManager     system_server                        W    Not force finishing home activity com.android.launcher3/.uioverrides.QuickstepLauncher
2024-12-19 12:13:14.048  2967-3167  ActivityManager         system_server                        I  Showing crash dialog for package com.android.launcher3 u0
2024-12-19 12:13:14.081  2967-3167  CoreBackPreview         system_server                        D  Window{b8bb943 u0 Application Error: com.android.launcher3}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@dbc02d8, mPriority=0, mIsAnimationCallback=false}
2024-12-19 12:13:14.106 12079-12079 CompatChangeReporter    com.google.android.deskclock         D  Compat change id reported: 63938206; UID 10186; state: ENABLED
2024-12-19 12:13:14.217  2967-3471  AppWidgetServiceImpl    system_server                        D  Trying to notify widget update for package com.google.android.deskclock with widget id: 3
```

Maybe something we can patch in launcher3

**Comment by NareshCal** [comment]
All Widgets works well on SD2 if Microsoft Launcher is used as default launcher (which is still my favorite for my muscle memory)

**Comment by Archfx** [comment]
This issue is still in A15-Alpha releases. Instead of relying on the system clock widget, I recommend this [clock](https://github.com/BlackyHawky/Clock) app.

**Comment by Archfx** [comment]
> Log on the issue:
> 
> ```
> 2024-12-19 12:13:14.025 12101-12101 b/267448330             com.android.launcher3                D  provider: ComponentInfo{com.google.android.deskclock/com.android.alarmclock.DigitalAppWidgetProvider}, paddedSizes: [331.19168x298.03107, 331.19168x298.03107, 435.23312x199.79274, 435.23312x199.79274], getMinMaxSizes: Rect(331, 199 - 435, 298)
> 2024-12-19 12:13:14.038  2967-3179  ActivityManager         system_server                        D  sync unfroze 12079 com.google.android.deskclock for 3
> 2024-12-19 12:13:14.042  2967-6483  AppWidgetServiceImpl    system_server                        I  Bound widget 3 to provider ProviderId{user:0, app:10186, 
> 2024-12-19 12:13:14.106 12079-12079 CompatChangeReporter    com.google.android.deskclock         D  Compat change id reported: 63938206; UID 10186; state: ENABLED
> 2024-12-19 12:13:14.217  2967-3471  AppWidgetServiceImpl    system_server                        D  Trying to notify widget update for package com.google.android.deskclock with widget id: 3
> ```
> 
> Maybe something we can patch in launcher3

Yeah, it looks like the issue is with the launcher. @NareshCal response confirms this as well.

**Comment by edgerunner995** [comment]
Its not only the clock in my Case. Every Widget causes an abort of the Launcher. Also setting a new Launcher isn't possible..
Also erases the Launcher Sometimes some Apps and widgets in the Homescreen.
